# Generated by Django 5.2.6 on 2025-10-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pvp_sugerido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pvp_corporativo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, help_text='Ej: 30 para 30%', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
