# Generated by Django 5.2.6 on 2025-10-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='mostrar_precios',
            field=models.BooleanField(default=True),
        ),
    ]
